os: linux
dist: xenial

services: docker

language: shell

branches:
  only:
    - main
    - master
    - develop

before_install:
  - env | sort
  - dir="images/${VERSION}/${VARIANT}"

install:
  - cd "$dir"
  # Execute CI build hooks
  - ./hooks/run build "${VARIANT}"

before_script:
  # Display docker images
  - docker images
  # FIXME Manually download OSM map
  #- sudo mkdir -p '/srv/osrm-backend/data/'
  #- sudo wget -O '/srv/osrm-backend/data/monaco-latest.osm.pbf' 'http://download.geofabrik.de/europe/monaco-latest.osm.pbf'

script:
  - cd "$dir"
  # Execute CI test hooks
  - ./hooks/run test "${VARIANT}"

notifications:
  email: false

env: # Environments
    - VERSION=latest VARIANT=debian
    - VERSION=5.21 VARIANT=debian
    - VERSION=5.22 VARIANT=debian
    - VERSION=5.23 VARIANT=debian
    - VERSION=5.24 VARIANT=debian
