
name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['5.22', '5.23']
        variant: ['debian']

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Execute CI build hooks
        id: docker_build
        run: |
          # Export variables to tag against GitHub Container Registry
          #export DOCKER_REGISTRY=ghcr.io
          #export DOCKER_REPO=${{ github.repository }}
          cd images/${VERSION}/${VARIANT}
          ./hooks/run build ${{ matrix.variant }}

      - name: Display docker images
        run: docker images

      - name: Execute CI test hooks
        id: docker_test
        run: |
          cd images/${VERSION}/${VARIANT}
          ./hooks/run test ${{ matrix.variant }}

      #- name: Execute CI push hooks
      #  id: docker_push
      #  run: |
      #    # Export variables to login and push to GitHub Container Registry
      #    #export DOCKER_REGISTRY=ghcr.io
      #    #export DOCKER_LOGIN=${{ github.repository_owner }}
      #    #export DOCKER_PASSWORD=${{ secrets.GITHUB_REGISTRY_TOKEN }}
      #    cd images/${VERSION}/${VARIANT}
      #    ./hooks/run push ${{ matrix.variant }}
